---
  - name: apt update
    apt: update_cache=yes cache_valid_time=3600
    register: apt_result
    until: apt_result|success
    retries: 3
    delay: 1
    become: yes
    ignore_errors: yes

  - name: retry if needed using command apt-get update
    command: apt-get update
    become: yes
    when: apt_result|failed
